# Generated by Django 4.2.11 on 2024-03-13 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0002_item_item_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="item_image",
        ),
    ]
